# Generated by Django 5.2.4 on 2025-08-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
